/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacle_jdk_NativeWithParamWithReturn */

#ifndef _Included_com_jacle_jdk_NativeWithParamWithReturn
#define _Included_com_jacle_jdk_NativeWithParamWithReturn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacle_jdk_NativeWithParamWithReturn
 * Method:    nativeWithParam
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacle_jdk_NativeWithParamWithReturn_nativeWithParam
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jacle_jdk_NativeWithParamWithReturn
 * Method:    nativeWithParamArr
 * Signature: (Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jacle_jdk_NativeWithParamWithReturn_nativeWithParamArr
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jacle_jdk_NativeWithParamWithReturn
 * Method:    nativeWithParamList
 * Signature: (Ljava/lang/String;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_jacle_jdk_NativeWithParamWithReturn_nativeWithParamList
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
