/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacle_jdk_NativeWithParamWithoutReturn */

#ifndef _Included_com_jacle_jdk_NativeWithParamWithoutReturn
#define _Included_com_jacle_jdk_NativeWithParamWithoutReturn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacle_jdk_NativeWithParamWithoutReturn
 * Method:    nativeWithParam
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jacle_jdk_NativeWithParamWithoutReturn_nativeWithParam
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
