/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacle_jdk_HelloNative */

#ifndef _Included_com_jacle_jdk_HelloNative
#define _Included_com_jacle_jdk_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacle_jdk_HelloNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacle_jdk_HelloNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
