/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacle_jdk_Native2 */

#ifndef _Included_com_jacle_jdk_Native2
#define _Included_com_jacle_jdk_Native2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacle_jdk_Native2
 * Method:    nativeHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacle_jdk_Native2_nativeHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
